# Day - 6 | Python Advanced

## Vectorization

A vector is a tuple of one or more values called scalars. Vectorization is the process of converting scalar data structure to vector format.

Vectorization helps to utilize modern SIMD instruction sets.

See the example https://numpy.org/doc/stable/user/whatisnumpy.html

- vectorized code is more concise and easier to read

- Fewer lines of code generally means fewer bugs

- The code more closely resembles standard mathematical notation (making it easier, typically, to correctly code mathematical constructs)

- Vectorization results in more “Pythonic” code. Without vectorization, our code would be littered with inefficient and difficult to read for loops.

## Introduction to numpy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

In [12]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a.shape)
#Dimensions are axis in numpy

(6,)
(3, 4)


In [22]:
import numpy as np

a1 = np.array([1,2,3,4,5])
print(a1)
a2 = np.zeros((2,4))
print(a2)
a3 = np.ones((4,4))
print(a3)
a4 = np.empty((1,4))
print(a4)
a5 = np.arange(5)
print(a5)
a6 = np.linspace(0, 10, num=5)
print(a6)
a7 = np.ones(2, dtype=np.int64)
print(a7)



[1 2 3 4 5]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 2.5  5.   7.5 10. ]]
[0 1 2 3 4]
[ 0.   2.5  5.   7.5 10. ]
[1 1]


Check this tutorial for other operations
https://numpy.org/doc/stable/user/absolute_beginners.html